services:
  drone-srcb: okteto context use https://cloud.okteto.com --namespace saverestrictedcontentbot-abhayabhay2000
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      SESSION: $SESSION
      AUTH: $AUTH
      FORCESUB: $FORCESUB
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
